import './Button/Button.stories';
import './Welcome/Welcome.stories';
import './MyBackNav.stories';
import './MyButton.stories';
import './MyEditIcon.stories';
import './MyInput.stories';
import './MyHeader.stories';
import './MyUploadMedia.stories';
import './MyStoryBox.stories';
// import './MyStory.stories';
// import './MySort.stories';
// import './MyTimePic.stories';
